### ISSUE TITLE
What does the name 'ds' stand for?

### ISSUE THREAD

**Issue by Kostekgol** [Jonathan-Uy/CSES-Solutions#4]
https://github.com/Jonathan-Uy/CSES-Solutions/blob/44c021dacb5dd81d72859f4fdf4f5e5111f42642/Graph%20Algorithms/Road%20Construction.cpp#L6

**Comment by Jonathan-Uy** [comment]
It is a [disjoint set](https://cp-algorithms.com/data_structures/disjoint_set_union.html) in this case.
