### ISSUE TITLE
What does "rt" stands for?

### ISSUE THREAD

**Issue by Kostekgol** [Jonathan-Uy/CSES-Solutions#6]
https://github.com/Jonathan-Uy/CSES-Solutions/blob/3d176342a6f0fc77cb03f92fe7e6ce811dd6e9bf/Graph%20Algorithms/Giant%20Pizza.cpp#L8

**Comment by Jonathan-Uy** [comment]
`rt[a]` is the SCC ID of `a`. That is, for two nodes `a` and `b`, we have `rt[a] == rt[b]` if and only if `a` and `b` belong to the same strongly connected component. It stands for "representative", so some others use `rep` as the variable name.
